version: '3.9'

services:
  springapi: 
    image: springdockertest
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - spring-networks

  postgres:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - spring-networks

volumes:
  postgres_data:

networks:
  spring-networks:
